//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrator.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaPoruka", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="Poruka")]
    [System.SerializableAttribute()]
    public class ListaPoruka : System.Collections.Generic.List<Administrator.ServiceReference1.Poruka> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Poruka", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class Poruka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPorukaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPosiljalacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPrimalacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IspisPorukeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TekstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VremeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPoruka {
            get {
                return this.IdPorukaField;
            }
            set {
                if ((this.IdPorukaField.Equals(value) != true)) {
                    this.IdPorukaField = value;
                    this.RaisePropertyChanged("IdPoruka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPosiljalac {
            get {
                return this.IdPosiljalacField;
            }
            set {
                if ((this.IdPosiljalacField.Equals(value) != true)) {
                    this.IdPosiljalacField = value;
                    this.RaisePropertyChanged("IdPosiljalac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPrimalac {
            get {
                return this.IdPrimalacField;
            }
            set {
                if ((this.IdPrimalacField.Equals(value) != true)) {
                    this.IdPrimalacField = value;
                    this.RaisePropertyChanged("IdPrimalac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IspisPoruke {
            get {
                return this.IspisPorukeField;
            }
            set {
                if ((object.ReferenceEquals(this.IspisPorukeField, value) != true)) {
                    this.IspisPorukeField = value;
                    this.RaisePropertyChanged("IspisPoruke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tekst {
            get {
                return this.TekstField;
            }
            set {
                if ((object.ReferenceEquals(this.TekstField, value) != true)) {
                    this.TekstField = value;
                    this.RaisePropertyChanged("Tekst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vreme {
            get {
                return this.VremeField;
            }
            set {
                if ((this.VremeField.Equals(value) != true)) {
                    this.VremeField = value;
                    this.RaisePropertyChanged("Vreme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KorisnickoImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LozinkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NadimakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickoIme {
            get {
                return this.KorisnickoImeField;
            }
            set {
                if ((object.ReferenceEquals(this.KorisnickoImeField, value) != true)) {
                    this.KorisnickoImeField = value;
                    this.RaisePropertyChanged("KorisnickoIme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka {
            get {
                return this.LozinkaField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true)) {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nadimak {
            get {
                return this.NadimakField;
            }
            set {
                if ((object.ReferenceEquals(this.NadimakField, value) != true)) {
                    this.NadimakField = value;
                    this.RaisePropertyChanged("Nadimak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tip {
            get {
                return this.TipField;
            }
            set {
                if ((this.TipField.Equals(value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaGrupa", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="Grupa")]
    [System.SerializableAttribute()]
    public class ListaGrupa : System.Collections.Generic.List<Administrator.ServiceReference1.Grupa> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupa", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class Grupa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxClanovaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxClanova {
            get {
                return this.MaxClanovaField;
            }
            set {
                if ((this.MaxClanovaField.Equals(value) != true)) {
                    this.MaxClanovaField = value;
                    this.RaisePropertyChanged("MaxClanova");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaGrupaKorisnika", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="GrupaKorisnik")]
    [System.SerializableAttribute()]
    public class ListaGrupaKorisnika : System.Collections.Generic.List<Administrator.ServiceReference1.GrupaKorisnik> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupaKorisnik", Namespace="http://schemas.datacontract.org/2004/07/Servis")]
    [System.SerializableAttribute()]
    public partial class GrupaKorisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdGrupeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdKorisnikaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrupe {
            get {
                return this.IdGrupeField;
            }
            set {
                if ((this.IdGrupeField.Equals(value) != true)) {
                    this.IdGrupeField = value;
                    this.RaisePropertyChanged("IdGrupe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKorisnika {
            get {
                return this.IdKorisnikaField;
            }
            set {
                if ((this.IdKorisnikaField.Equals(value) != true)) {
                    this.IdKorisnikaField = value;
                    this.RaisePropertyChanged("IdKorisnika");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaKorisnika", Namespace="http://schemas.datacontract.org/2004/07/Servis", ItemName="Korisnik")]
    [System.SerializableAttribute()]
    public class ListaKorisnika : System.Collections.Generic.List<Administrator.ServiceReference1.Korisnik> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimiPoruku", ReplyAction="http://tempuri.org/IService1/PrimiPorukuResponse")]
        void PrimiPoruku(int idPosiljalac, string tekst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimiPoruku", ReplyAction="http://tempuri.org/IService1/PrimiPorukuResponse")]
        System.Threading.Tasks.Task PrimiPorukuAsync(int idPosiljalac, string tekst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebPrimiPoruku", ReplyAction="http://tempuri.org/IService1/WebPrimiPorukuResponse")]
        string WebPrimiPoruku(System.IO.Stream podaci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebPrimiPoruku", ReplyAction="http://tempuri.org/IService1/WebPrimiPorukuResponse")]
        System.Threading.Tasks.Task<string> WebPrimiPorukuAsync(System.IO.Stream podaci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiPoruke", ReplyAction="http://tempuri.org/IService1/VratiPorukeResponse")]
        Administrator.ServiceReference1.ListaPoruka VratiPoruke(int idKorisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiPoruke", ReplyAction="http://tempuri.org/IService1/VratiPorukeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaPoruka> VratiPorukeAsync(int idKorisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebUlogujKorisnika", ReplyAction="http://tempuri.org/IService1/WebUlogujKorisnikaResponse")]
        Administrator.ServiceReference1.Korisnik WebUlogujKorisnika(System.IO.Stream podaci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebUlogujKorisnika", ReplyAction="http://tempuri.org/IService1/WebUlogujKorisnikaResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.Korisnik> WebUlogujKorisnikaAsync(System.IO.Stream podaci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UlogujKorisnika", ReplyAction="http://tempuri.org/IService1/UlogujKorisnikaResponse")]
        Administrator.ServiceReference1.Korisnik UlogujKorisnika(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UlogujKorisnika", ReplyAction="http://tempuri.org/IService1/UlogujKorisnikaResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.Korisnik> UlogujKorisnikaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DodajKorisnika", ReplyAction="http://tempuri.org/IService1/DodajKorisnikaResponse")]
        void DodajKorisnika(string korisnicko_ime, string lozinka, string nadimak, bool tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DodajKorisnika", ReplyAction="http://tempuri.org/IService1/DodajKorisnikaResponse")]
        System.Threading.Tasks.Task DodajKorisnikaAsync(string korisnicko_ime, string lozinka, string nadimak, bool tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IzmeniKorisnika", ReplyAction="http://tempuri.org/IService1/IzmeniKorisnikaResponse")]
        void IzmeniKorisnika(int id, string korisnicko_ime, string lozinka, string nadimak, bool tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IzmeniKorisnika", ReplyAction="http://tempuri.org/IService1/IzmeniKorisnikaResponse")]
        System.Threading.Tasks.Task IzmeniKorisnikaAsync(int id, string korisnicko_ime, string lozinka, string nadimak, bool tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObrisiKorisnika", ReplyAction="http://tempuri.org/IService1/ObrisiKorisnikaResponse")]
        void ObrisiKorisnika(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObrisiKorisnika", ReplyAction="http://tempuri.org/IService1/ObrisiKorisnikaResponse")]
        System.Threading.Tasks.Task ObrisiKorisnikaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DodajGrupu", ReplyAction="http://tempuri.org/IService1/DodajGrupuResponse")]
        void DodajGrupu(string naziv, int maxClanova);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DodajGrupu", ReplyAction="http://tempuri.org/IService1/DodajGrupuResponse")]
        System.Threading.Tasks.Task DodajGrupuAsync(string naziv, int maxClanova);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IzmeniGrupu", ReplyAction="http://tempuri.org/IService1/IzmeniGrupuResponse")]
        void IzmeniGrupu(int id, string naziv, int maxClanova);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IzmeniGrupu", ReplyAction="http://tempuri.org/IService1/IzmeniGrupuResponse")]
        System.Threading.Tasks.Task IzmeniGrupuAsync(int id, string naziv, int maxClanova);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObrisiGrupu", ReplyAction="http://tempuri.org/IService1/ObrisiGrupuResponse")]
        void ObrisiGrupu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObrisiGrupu", ReplyAction="http://tempuri.org/IService1/ObrisiGrupuResponse")]
        System.Threading.Tasks.Task ObrisiGrupuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiGrupe", ReplyAction="http://tempuri.org/IService1/VratiGrupeResponse")]
        Administrator.ServiceReference1.ListaGrupa VratiGrupe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiGrupe", ReplyAction="http://tempuri.org/IService1/VratiGrupeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupa> VratiGrupeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimanjeZahtevaZaGrupu", ReplyAction="http://tempuri.org/IService1/PrimanjeZahtevaZaGrupuResponse")]
        void PrimanjeZahtevaZaGrupu(int idKorisnika, int idZeljeneGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimanjeZahtevaZaGrupu", ReplyAction="http://tempuri.org/IService1/PrimanjeZahtevaZaGrupuResponse")]
        System.Threading.Tasks.Task PrimanjeZahtevaZaGrupuAsync(int idKorisnika, int idZeljeneGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiZahteveZaGrupu", ReplyAction="http://tempuri.org/IService1/VratiZahteveZaGrupuResponse")]
        Administrator.ServiceReference1.ListaGrupaKorisnika VratiZahteveZaGrupu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiZahteveZaGrupu", ReplyAction="http://tempuri.org/IService1/VratiZahteveZaGrupuResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupaKorisnika> VratiZahteveZaGrupuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OdobravanjeZahtevaZaGrupu", ReplyAction="http://tempuri.org/IService1/OdobravanjeZahtevaZaGrupuResponse")]
        bool OdobravanjeZahtevaZaGrupu(int idKorisnika, int idZeljeneGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OdobravanjeZahtevaZaGrupu", ReplyAction="http://tempuri.org/IService1/OdobravanjeZahtevaZaGrupuResponse")]
        System.Threading.Tasks.Task<bool> OdobravanjeZahtevaZaGrupuAsync(int idKorisnika, int idZeljeneGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RucnoDodavanjeKorisnikaUGrupu", ReplyAction="http://tempuri.org/IService1/RucnoDodavanjeKorisnikaUGrupuResponse")]
        bool RucnoDodavanjeKorisnikaUGrupu(int idKorisnika, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RucnoDodavanjeKorisnikaUGrupu", ReplyAction="http://tempuri.org/IService1/RucnoDodavanjeKorisnikaUGrupuResponse")]
        System.Threading.Tasks.Task<bool> RucnoDodavanjeKorisnikaUGrupuAsync(int idKorisnika, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IzlazakIzGrupe", ReplyAction="http://tempuri.org/IService1/IzlazakIzGrupeResponse")]
        void IzlazakIzGrupe(int idKorisnika, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IzlazakIzGrupe", ReplyAction="http://tempuri.org/IService1/IzlazakIzGrupeResponse")]
        System.Threading.Tasks.Task IzlazakIzGrupeAsync(int idKorisnika, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiKorisnike", ReplyAction="http://tempuri.org/IService1/VratiKorisnikeResponse")]
        Administrator.ServiceReference1.ListaKorisnika VratiKorisnike();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiKorisnike", ReplyAction="http://tempuri.org/IService1/VratiKorisnikeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaKorisnika> VratiKorisnikeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiGrupeUKojimaNije", ReplyAction="http://tempuri.org/IService1/VratiGrupeUKojimaNijeResponse")]
        Administrator.ServiceReference1.ListaGrupa VratiGrupeUKojimaNije(int idKorisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VratiGrupeUKojimaNije", ReplyAction="http://tempuri.org/IService1/VratiGrupeUKojimaNijeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupa> VratiGrupeUKojimaNijeAsync(int idKorisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebVratiGrupeUKojimaNije", ReplyAction="http://tempuri.org/IService1/WebVratiGrupeUKojimaNijeResponse")]
        Administrator.ServiceReference1.ListaGrupa WebVratiGrupeUKojimaNije(System.IO.Stream podaci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebVratiGrupeUKojimaNije", ReplyAction="http://tempuri.org/IService1/WebVratiGrupeUKojimaNijeResponse")]
        System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupa> WebVratiGrupeUKojimaNijeAsync(System.IO.Stream podaci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Administrator.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Administrator.ServiceReference1.IService1>, Administrator.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PrimiPoruku(int idPosiljalac, string tekst) {
            base.Channel.PrimiPoruku(idPosiljalac, tekst);
        }
        
        public System.Threading.Tasks.Task PrimiPorukuAsync(int idPosiljalac, string tekst) {
            return base.Channel.PrimiPorukuAsync(idPosiljalac, tekst);
        }
        
        public string WebPrimiPoruku(System.IO.Stream podaci) {
            return base.Channel.WebPrimiPoruku(podaci);
        }
        
        public System.Threading.Tasks.Task<string> WebPrimiPorukuAsync(System.IO.Stream podaci) {
            return base.Channel.WebPrimiPorukuAsync(podaci);
        }
        
        public Administrator.ServiceReference1.ListaPoruka VratiPoruke(int idKorisnika) {
            return base.Channel.VratiPoruke(idKorisnika);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaPoruka> VratiPorukeAsync(int idKorisnika) {
            return base.Channel.VratiPorukeAsync(idKorisnika);
        }
        
        public Administrator.ServiceReference1.Korisnik WebUlogujKorisnika(System.IO.Stream podaci) {
            return base.Channel.WebUlogujKorisnika(podaci);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.Korisnik> WebUlogujKorisnikaAsync(System.IO.Stream podaci) {
            return base.Channel.WebUlogujKorisnikaAsync(podaci);
        }
        
        public Administrator.ServiceReference1.Korisnik UlogujKorisnika(string username, string password) {
            return base.Channel.UlogujKorisnika(username, password);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.Korisnik> UlogujKorisnikaAsync(string username, string password) {
            return base.Channel.UlogujKorisnikaAsync(username, password);
        }
        
        public void DodajKorisnika(string korisnicko_ime, string lozinka, string nadimak, bool tip) {
            base.Channel.DodajKorisnika(korisnicko_ime, lozinka, nadimak, tip);
        }
        
        public System.Threading.Tasks.Task DodajKorisnikaAsync(string korisnicko_ime, string lozinka, string nadimak, bool tip) {
            return base.Channel.DodajKorisnikaAsync(korisnicko_ime, lozinka, nadimak, tip);
        }
        
        public void IzmeniKorisnika(int id, string korisnicko_ime, string lozinka, string nadimak, bool tip) {
            base.Channel.IzmeniKorisnika(id, korisnicko_ime, lozinka, nadimak, tip);
        }
        
        public System.Threading.Tasks.Task IzmeniKorisnikaAsync(int id, string korisnicko_ime, string lozinka, string nadimak, bool tip) {
            return base.Channel.IzmeniKorisnikaAsync(id, korisnicko_ime, lozinka, nadimak, tip);
        }
        
        public void ObrisiKorisnika(int id) {
            base.Channel.ObrisiKorisnika(id);
        }
        
        public System.Threading.Tasks.Task ObrisiKorisnikaAsync(int id) {
            return base.Channel.ObrisiKorisnikaAsync(id);
        }
        
        public void DodajGrupu(string naziv, int maxClanova) {
            base.Channel.DodajGrupu(naziv, maxClanova);
        }
        
        public System.Threading.Tasks.Task DodajGrupuAsync(string naziv, int maxClanova) {
            return base.Channel.DodajGrupuAsync(naziv, maxClanova);
        }
        
        public void IzmeniGrupu(int id, string naziv, int maxClanova) {
            base.Channel.IzmeniGrupu(id, naziv, maxClanova);
        }
        
        public System.Threading.Tasks.Task IzmeniGrupuAsync(int id, string naziv, int maxClanova) {
            return base.Channel.IzmeniGrupuAsync(id, naziv, maxClanova);
        }
        
        public void ObrisiGrupu(int id) {
            base.Channel.ObrisiGrupu(id);
        }
        
        public System.Threading.Tasks.Task ObrisiGrupuAsync(int id) {
            return base.Channel.ObrisiGrupuAsync(id);
        }
        
        public Administrator.ServiceReference1.ListaGrupa VratiGrupe() {
            return base.Channel.VratiGrupe();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupa> VratiGrupeAsync() {
            return base.Channel.VratiGrupeAsync();
        }
        
        public void PrimanjeZahtevaZaGrupu(int idKorisnika, int idZeljeneGrupe) {
            base.Channel.PrimanjeZahtevaZaGrupu(idKorisnika, idZeljeneGrupe);
        }
        
        public System.Threading.Tasks.Task PrimanjeZahtevaZaGrupuAsync(int idKorisnika, int idZeljeneGrupe) {
            return base.Channel.PrimanjeZahtevaZaGrupuAsync(idKorisnika, idZeljeneGrupe);
        }
        
        public Administrator.ServiceReference1.ListaGrupaKorisnika VratiZahteveZaGrupu() {
            return base.Channel.VratiZahteveZaGrupu();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupaKorisnika> VratiZahteveZaGrupuAsync() {
            return base.Channel.VratiZahteveZaGrupuAsync();
        }
        
        public bool OdobravanjeZahtevaZaGrupu(int idKorisnika, int idZeljeneGrupe) {
            return base.Channel.OdobravanjeZahtevaZaGrupu(idKorisnika, idZeljeneGrupe);
        }
        
        public System.Threading.Tasks.Task<bool> OdobravanjeZahtevaZaGrupuAsync(int idKorisnika, int idZeljeneGrupe) {
            return base.Channel.OdobravanjeZahtevaZaGrupuAsync(idKorisnika, idZeljeneGrupe);
        }
        
        public bool RucnoDodavanjeKorisnikaUGrupu(int idKorisnika, int idGrupe) {
            return base.Channel.RucnoDodavanjeKorisnikaUGrupu(idKorisnika, idGrupe);
        }
        
        public System.Threading.Tasks.Task<bool> RucnoDodavanjeKorisnikaUGrupuAsync(int idKorisnika, int idGrupe) {
            return base.Channel.RucnoDodavanjeKorisnikaUGrupuAsync(idKorisnika, idGrupe);
        }
        
        public void IzlazakIzGrupe(int idKorisnika, int idGrupe) {
            base.Channel.IzlazakIzGrupe(idKorisnika, idGrupe);
        }
        
        public System.Threading.Tasks.Task IzlazakIzGrupeAsync(int idKorisnika, int idGrupe) {
            return base.Channel.IzlazakIzGrupeAsync(idKorisnika, idGrupe);
        }
        
        public Administrator.ServiceReference1.ListaKorisnika VratiKorisnike() {
            return base.Channel.VratiKorisnike();
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaKorisnika> VratiKorisnikeAsync() {
            return base.Channel.VratiKorisnikeAsync();
        }
        
        public Administrator.ServiceReference1.ListaGrupa VratiGrupeUKojimaNije(int idKorisnik) {
            return base.Channel.VratiGrupeUKojimaNije(idKorisnik);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupa> VratiGrupeUKojimaNijeAsync(int idKorisnik) {
            return base.Channel.VratiGrupeUKojimaNijeAsync(idKorisnik);
        }
        
        public Administrator.ServiceReference1.ListaGrupa WebVratiGrupeUKojimaNije(System.IO.Stream podaci) {
            return base.Channel.WebVratiGrupeUKojimaNije(podaci);
        }
        
        public System.Threading.Tasks.Task<Administrator.ServiceReference1.ListaGrupa> WebVratiGrupeUKojimaNijeAsync(System.IO.Stream podaci) {
            return base.Channel.WebVratiGrupeUKojimaNijeAsync(podaci);
        }
    }
}
